### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by LY-1** [GC-WSL/MOL#3]
首先感谢您的贡献，让我受益非浅。然后再请问能提供dior的一阶段的结果吗，corloc和voc map的评价指标是怎么生成的

**Comment by GC-WSL** [comment]
Thank you for your attention. We have uploaded the pseudo-labels of the DIOR dataset generated by MOL-1 (MOL/MOL-2/cvpods/datasets/DIOR)
. We follow https://github.com/vasgaowei/D-MIL.pytorch/tree/master/lib/datasets/dis_eval.py to calculate the Corloc metric.

**Comment by LY-1** [comment]
请问cvopods能不能保存训练过程中最好的权重还有应该怎么修改验证的步长

**Comment by GC-WSL** [comment]
你好，感谢关注！我们直接保存了最后一代的权重，并没有对每一代都测试并取最优，那样的对比在弱监督场景下是不公平的（弱监督场景训练过程中应当避免正确标签的参与），可以通过修改SOLVER.VAL_PERIOD参数，改变验证步长。
